package com.keytrins.kucoingrid;

import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.Typeface;import android.text.InputType;import android.view.*;import android.widget.*;import java.util.*;

public class MainActivity extends Activity {
 private EditText key,secret,pass,symbol,capital,lev,levels,dayLoss,posLoss,protectStep,protectLag;private Switch live;private TextView log;private BroadcastReceiver rx;private CredentialStore credentialStore;
 @Override public void onCreate(Bundle b){super.onCreate(b);credentialStore=new CredentialStore(this);if(Build.VERSION.SDK_INT>=33&&checkSelfPermission("android.permission.POST_NOTIFICATIONS")!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{"android.permission.POST_NOTIFICATIONS"},7);build();restoreCredentials();rx=new BroadcastReceiver(){public void onReceive(Context c,Intent i){String t=i.getStringExtra("text");log.append(time()+"  "+t+"\n");}};registerReceiver(rx,new IntentFilter(GridService.ACTION_LOG),Build.VERSION.SDK_INT>=33?Context.RECEIVER_NOT_EXPORTED:0);}
 private void build(){ScrollView sv=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(28,28,28,48);sv.addView(root);TextView title=new TextView(this);title.setText("KuCoin Adaptive Grid 0.2.1");title.setTextSize(24);title.setTypeface(Typeface.DEFAULT_BOLD);root.addView(title);TextView sub=new TextView(this);sub.setText("Полный GRID-цикл • risk guard • auto margin mode • encrypted keys");sub.setPadding(0,4,0,20);root.addView(sub);
  key=field(root,"API Key","");secret=field(root,"API Secret","");secret.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);pass=field(root,"API Passphrase","");pass.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);
  Button clearKeys=new Button(this);clearKeys.setText("ОЧИСТИТЬ СОХРАНЁННЫЕ КЛЮЧИ");clearKeys.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Удалить сохранённые ключи?").setMessage("API Key, Secret и Passphrase будут удалены только с этого устройства.").setNegativeButton("ОТМЕНА",null).setPositiveButton("УДАЛИТЬ",(d,w)->{credentialStore.clear();key.setText("");secret.setText("");pass.setText("");Toast.makeText(this,"Сохранённые ключи удалены",Toast.LENGTH_SHORT).show();}).show());root.addView(clearKeys);
  symbol=field(root,"Контракт","DOGEUSDTM");capital=field(root,"Капитал робота, USDT","100");lev=field(root,"Плечо","2");levels=field(root,"Максимум уровней в сторону","5");dayLoss=field(root,"Макс. дневной убыток, % капитала","3");posLoss=field(root,"Аварийный убыток позиции, % капитала","1.5");protectStep=field(root,"Шаг денежной защиты, USDT","1");protectLag=field(root,"Отставание денежной защиты, USDT","1");
  live=new Switch(this);live.setText("LIVE торговля (ВЫКЛ = безопасный /orders/test)");live.setChecked(false);root.addView(live);TextView warn=new TextView(this);warn.setText("API-ключи после первого запуска сохраняются на этом телефоне в зашифрованном виде через Android Keystore; в GitHub и в APK они не записываются. LIVE: реальные KuCoin Futures ордера. Робот автоматически читает margin mode CROSS/ISOLATED для контракта; при 330005 перечитывает его и повторяет заявку один раз. Отменяются только ордера KAG2. Fill уровня → reduce-only выход → восстановление уровня. При SHOCK набор прекращается.");warn.setPadding(0,12,0,16);root.addView(warn);
  LinearLayout row=new LinearLayout(this);Button start=new Button(this);start.setText("ЗАПУСТИТЬ");Button stop=new Button(this);stop.setText("СТОП");row.addView(start,new LinearLayout.LayoutParams(0,-2,1));row.addView(stop,new LinearLayout.LayoutParams(0,-2,1));root.addView(row);log=new TextView(this);log.setText("Журнал:\n");log.setTextIsSelectable(true);log.setPadding(0,20,0,0);root.addView(log);start.setOnClickListener(v->start());stop.setOnClickListener(v->{Intent i=new Intent(this,GridService.class);i.setAction("STOP");startService(i);});setContentView(sv);}
 private void restoreCredentials(){CredentialStore.Credentials c=credentialStore.load();if(c!=null){key.setText(c.key);secret.setText(c.secret);pass.setText(c.pass);}}
 private EditText field(LinearLayout r,String hint,String val){TextView l=new TextView(this);l.setText(hint);r.addView(l);EditText e=new EditText(this);e.setText(val);e.setSingleLine(true);r.addView(e,new LinearLayout.LayoutParams(-1,-2));return e;}
 private void start(){try{String k=key.getText().toString().trim(),s=secret.getText().toString().trim(),p=pass.getText().toString();if(k.isEmpty()||s.isEmpty()||p.trim().isEmpty()){Toast.makeText(this,"Введите API Key / Secret / Passphrase",Toast.LENGTH_LONG).show();return;}credentialStore.save(k,s,p);double cap=Double.parseDouble(capital.getText().toString()),dl=Double.parseDouble(dayLoss.getText().toString()),pl=Double.parseDouble(posLoss.getText().toString()),ps=Double.parseDouble(protectStep.getText().toString()),pg=Double.parseDouble(protectLag.getText().toString());int lv=Integer.parseInt(lev.getText().toString()),ls=Integer.parseInt(levels.getText().toString());if(cap<=0||lv<1||lv>20||ls<1||ls>20||dl<=0||pl<=0||ps<=0||pg<0)throw new IllegalArgumentException("Проверьте числовые настройки");Intent i=new Intent(this,GridService.class);i.putExtra("key",k);i.putExtra("secret",s);i.putExtra("pass",p);i.putExtra("symbol",symbol.getText().toString().trim().toUpperCase(Locale.US));i.putExtra("capital",cap);i.putExtra("lev",lv);i.putExtra("levels",ls);i.putExtra("dayLoss",dl);i.putExtra("posLoss",pl);i.putExtra("protectStep",ps);i.putExtra("protectLag",pg);i.putExtra("test",!live.isChecked());if(live.isChecked())new AlertDialog.Builder(this).setTitle("Запустить LIVE?").setMessage("Будут выставляться РЕАЛЬНЫЕ фьючерсные ордера KuCoin.").setNegativeButton("ОТМЕНА",null).setPositiveButton("ДА, LIVE",(d,w)->startServiceSafe(i)).show();else startServiceSafe(i);}catch(Exception e){Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show();}}
 private void startServiceSafe(Intent i){startForegroundService(i);}
 private String time(){return new java.text.SimpleDateFormat("HH:mm:ss",Locale.US).format(new Date());}
 @Override protected void onDestroy(){if(rx!=null)unregisterReceiver(rx);super.onDestroy();}
}
