package com.keytrins.kucoingrid;

import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.Typeface;import android.view.*;import android.widget.*;import java.util.*;

public class MainActivity extends Activity {
 private EditText key,secret,pass,symbol,capital,lev,levels; private Switch live; private TextView log; private BroadcastReceiver rx;
 @Override public void onCreate(Bundle b){super.onCreate(b); if(Build.VERSION.SDK_INT>=33&&checkSelfPermission("android.permission.POST_NOTIFICATIONS")!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{"android.permission.POST_NOTIFICATIONS"},7); build(); rx=new BroadcastReceiver(){public void onReceive(Context c,Intent i){String t=i.getStringExtra("text");log.append(time()+"  "+t+"\n");}}; registerReceiver(rx,new IntentFilter(GridService.ACTION_LOG),Build.VERSION.SDK_INT>=33?Context.RECEIVER_NOT_EXPORTED:0);}
 private void build(){ScrollView sv=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(28,28,28,48);sv.addView(root);TextView title=new TextView(this);title.setText("KuCoin Adaptive Grid 0.1.0");title.setTextSize(24);title.setTypeface(Typeface.DEFAULT_BOLD);root.addView(title);TextView sub=new TextView(this);sub.setText("Futures • RANGE / TREND / SHOCK • по умолчанию TEST");sub.setPadding(0,4,0,20);root.addView(sub);
  key=field(root,"API Key","");secret=field(root,"API Secret","");pass=field(root,"API Passphrase","");symbol=field(root,"Контракт","DOGEUSDTM");capital=field(root,"Капитал робота, USDT","100");lev=field(root,"Плечо","2");levels=field(root,"Максимум уровней в сторону","5");
  live=new Switch(this);live.setText("LIVE торговля (ВЫКЛ = безопасный /orders/test)");live.setChecked(false);root.addView(live);TextView warn=new TextView(this);warn.setText("В LIVE робот выставляет реальные фьючерсные ордера. Используйте API-ключ без права вывода средств. При SHOCK новые ордера снимаются и сетка замораживается. Для v0.1 используется One-Way Position Mode.");warn.setPadding(0,12,0,16);root.addView(warn);
  LinearLayout row=new LinearLayout(this);Button start=new Button(this);start.setText("ЗАПУСТИТЬ");Button stop=new Button(this);stop.setText("СТОП");row.addView(start,new LinearLayout.LayoutParams(0,-2,1));row.addView(stop,new LinearLayout.LayoutParams(0,-2,1));root.addView(row); log=new TextView(this);log.setText("Журнал:\n");log.setTextIsSelectable(true);log.setPadding(0,20,0,0);root.addView(log);start.setOnClickListener(v->start());stop.setOnClickListener(v->{Intent i=new Intent(this,GridService.class);i.setAction("STOP");startService(i);});setContentView(sv);}
 private EditText field(LinearLayout r,String hint,String val){TextView l=new TextView(this);l.setText(hint);r.addView(l);EditText e=new EditText(this);e.setText(val);e.setSingleLine(true);r.addView(e,new LinearLayout.LayoutParams(-1,-2));return e;}
 private void start(){try{if(key.getText().toString().trim().isEmpty()||secret.getText().toString().trim().isEmpty()||pass.getText().toString().trim().isEmpty()){Toast.makeText(this,"Введите API Key / Secret / Passphrase",Toast.LENGTH_LONG).show();return;}Intent i=new Intent(this,GridService.class);i.putExtra("key",key.getText().toString().trim());i.putExtra("secret",secret.getText().toString().trim());i.putExtra("pass",pass.getText().toString());i.putExtra("symbol",symbol.getText().toString().trim().toUpperCase(Locale.US));i.putExtra("capital",Double.parseDouble(capital.getText().toString()));i.putExtra("lev",Integer.parseInt(lev.getText().toString()));i.putExtra("levels",Integer.parseInt(levels.getText().toString()));i.putExtra("test",!live.isChecked());startForegroundService(i);}catch(Exception e){Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show();}}
 private String time(){return new java.text.SimpleDateFormat("HH:mm:ss",Locale.US).format(new Date());}
 @Override protected void onDestroy(){if(rx!=null)unregisterReceiver(rx);super.onDestroy();}
}
